# Generated by Django 3.2.20 on 2024-03-24 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('previous_hash', models.CharField(max_length=256)),
                ('timestamp', models.DateTimeField()),
                ('nonce', models.IntegerField()),
                ('hash', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter', models.CharField(max_length=100)),
                ('candidate', models.CharField(max_length=100)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.block')),
            ],
        ),
    ]
