# Generated by Django 3.2.25 on 2024-11-13 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_block_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='voter_photos/%Y/%m/%d/')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='voting.voter')),
            ],
            options={
                'ordering': ['captured_at'],
            },
        ),
    ]
